[package]
name = "exhume_metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
exhume_partitions = { path = "../exhume_partitions" }
exhume_readers = { path = "../exhume_readers" }
log = "0.4.17"
